sudo: required

services:
  - docker

after_success:
  - sha256sum build/* > build/SHA256SUMS
  - cat build/SHA256SUMS

script: |-
  version=$(grep '"version":' src/drivers/webextension/manifest.json | sed 's/^.*"version": "\(.*\)".*$/\1/'); ./run build $version

deploy:
  provider: releases
  api_key:
    secure: mco1ycbfGXZEiBywOmM5A50Y1QPFawj4i0gdB9JDkXDvY7N2kPZyCdAeOQOMEJuetGT3HvJuTG0Ll47sithZfPqq6wx/4EeP8YQYYFIyoOlsIGi5MDR1kS5ZOqKDWGe5+x+/rUZbmuMHvgHWNSjPG8mBrp5xWmON6ETkLWfVB0c=
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    repo: AliasIO/Wappalyzer
    tags: true

env:
  - CXX=g++-4.8
